CREATE TABLE EMUNAH.CDEXT (
    EXT_AGENCIA      CHAR(4)         NOT NULL,
    EXT_NUM_CONTA    CHAR(8)         NOT NULL,
    EXT_DATA_MOVTO   DATE            NOT NULL,
    EXT_NSEQ         DECIMAL(6,0)    NOT NULL,
    EXT_TIPO         CHAR(1)         NOT NULL,
    EXT_DESCRICAO    CHAR(30)        NOT NULL WITH DEFAULT,
    EXT_VALOR        DECIMAL(13,2)   NOT NULL,
    EXT_SALDO_APOS   DECIMAL(13,2)   NOT NULL,
    EXT_CANAL        CHAR(10)        NOT NULL WITH DEFAULT,
    EXT_DT_CARGA     TIMESTAMP       NOT NULL WITH DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CDEXT
        PRIMARY KEY (EXT_AGENCIA, EXT_NUM_CONTA, EXT_DATA_MOVTO, EXT_NSEQ),
    CONSTRAINT CK_CDEXT_TIPO
        CHECK (EXT_TIPO IN ('C','D'))
)