//* ============================================================
//* ARQUIVO      : EBJBCKPD.jcl
//* CAMINHO LOCAL: jcl/batch/EBJBCKPD.jcl
//* HOST / PDS   : Z77948.EMUNAH.DEV.JCL(EBJBCKPD)
//*
//* FINALIDADE:
//* Realizar o backup diario dos datasets do Emunah Bank.
//* Gera novas geracoes (+1) para as GDGs de seguranca.
//* ============================================================
//EBJBCKPD JOB ,'EMUNAH BKP',CLASS=A,MSGCLASS=X,MSGLEVEL=(1,1)
//*
//* === STEP BKPCLI: BACKUP DE CLIENTES (KSDS -> GDG) ==========
//BKPCLI   EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//INFILE   DD DSN=Z77948.EMUNAH.ARQ.CLIENTE.KSDS,DISP=SHR
//OUTFILE  DD DSN=Z77948.EMUNAH.BKP.CLIENTE.GDG(+1),
//            DISP=(NEW,CATLG,DELETE),
//            UNIT=SYSDA,SPACE=(TRK,(5,5)),
//            DCB=(RECFM=FB,LRECL=80,BLKSIZE=0)
//SYSIN    DD *
  REPRO INFILE(INFILE) OUTFILE(OUTFILE)
/*
//*
//* === STEP BKPCNT: BACKUP DE CONTAS (KSDS -> GDG) ============
//BKPCNT   EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//INFILE   DD DSN=Z77948.EMUNAH.ARQ.CONTA.KSDS,DISP=SHR
//OUTFILE  DD DSN=Z77948.EMUNAH.BKP.CONTA.GDG(+1),
//            DISP=(NEW,CATLG,DELETE),
//            UNIT=SYSDA,SPACE=(TRK,(5,5)),
//            DCB=(RECFM=FB,LRECL=100,BLKSIZE=0)
//SYSIN    DD *
  REPRO INFILE(INFILE) OUTFILE(OUTFILE)
/*
//*
//* === STEP BKPAUD: BACKUP DE AUDITORIA (SEQ -> GDG) ==========
//BKPAUD   EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//INFILE   DD DSN=Z77948.EMUNAH.ARQ.AUDIT.SEQ,DISP=SHR
//OUTFILE  DD DSN=Z77948.EMUNAH.BKP.AUDIT.GDG(+1),
//            DISP=(NEW,CATLG,DELETE),
//            UNIT=SYSDA,SPACE=(TRK,(10,5)),
//            LIKE=Z77948.EMUNAH.ARQ.AUDIT.SEQ
//SYSIN    DD *
  REPRO INFILE(INFILE) OUTFILE(OUTFILE)
/*
//*
//* === STEP BKPREJ: BACKUP DE REJEITOS (SEQ -> GDG) ===========
//BKPREJ   EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//INFILE   DD DSN=Z77948.EMUNAH.ARQ.REJEITOS.SEQ,DISP=SHR
//OUTFILE  DD DSN=Z77948.EMUNAH.BKP.REJEITOS.GDG(+1),
//            DISP=(NEW,CATLG,DELETE),
//            UNIT=SYSDA,SPACE=(TRK,(5,5)),
//            LIKE=Z77948.EMUNAH.ARQ.REJEITOS.SEQ
//SYSIN    DD *
  REPRO INFILE(INFILE) OUTFILE(OUTFILE)
  IF LASTCC = 4 THEN - 
     SET MAXCC = 0
/*
//*
//* === STEP BKPCNC: BACKUP DE CONCILIACAO (SEQ -> GDG) ========
//BKPCNC   EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//INFILE   DD DSN=Z77948.EMUNAH.ARQ.CONCIL.SEQ,DISP=SHR
//OUTFILE  DD DSN=Z77948.EMUNAH.BKP.CONCIL.GDG(+1),
//            DISP=(NEW,CATLG,DELETE),
//            UNIT=SYSDA,SPACE=(TRK,(10,5)),
//            LIKE=Z77948.EMUNAH.ARQ.CONCIL.SEQ
//SYSIN    DD *
  REPRO INFILE(INFILE) OUTFILE(OUTFILE)
/*