--=============================================================--
-- EMUNAH BANK LAB - DB2 DDL (VERSAO LIMPA SEM COMENTARIOS INLINE)
--=============================================================--

-- TABELA 1: CLIENTES
CREATE TABLE EMUNAH.CLIENTES (
    CLI_ID_CLIENTE   DECIMAL(5, 0)   NOT NULL,
    CLI_NOME         CHAR(30)        NOT NULL,
    CLI_CPF          CHAR(11)        NOT NULL,
    CLI_DATA_NASC    CHAR(8)         NOT NULL,
    CLI_STATUS       CHAR(1)         NOT NULL WITH DEFAULT 'A',
    CLI_DATA_CAD     CHAR(8)         NOT NULL,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (CLI_ID_CLIENTE),
    CONSTRAINT CK_CLI_STATUS CHECK (CLI_STATUS IN ('A','I','B')),
    CONSTRAINT CK_CLI_CPF_LEN CHECK (LENGTH(TRIM(CLI_CPF)) = 11)
);

-- TABELA 2: CONTAS
CREATE TABLE EMUNAH.CONTAS (
    CNT_AGENCIA       CHAR(4)         NOT NULL,
    CNT_NUM_CONTA     CHAR(8)         NOT NULL,
    CNT_ID_CLIENTE    DECIMAL(5, 0)   NOT NULL,
    CNT_TIPO          CHAR(1)         NOT NULL,
    CNT_STATUS        CHAR(1)         NOT NULL WITH DEFAULT 'A',
    CNT_DATA_ABERTURA CHAR(8)         NOT NULL,
    CNT_SALDO         DECIMAL(13, 2)  NOT NULL WITH DEFAULT 0,
    CNT_LIMITE        DECIMAL(11, 2)  NOT NULL WITH DEFAULT 0,
    CONSTRAINT PK_CONTAS PRIMARY KEY (CNT_AGENCIA, CNT_NUM_CONTA),
    CONSTRAINT FK_CONTAS_CLIENTES FOREIGN KEY (CNT_ID_CLIENTE)
        REFERENCES EMUNAH.CLIENTES (CLI_ID_CLIENTE),
    CONSTRAINT CK_CNT_TIPO   CHECK (CNT_TIPO   IN ('C','P','S')),
    CONSTRAINT CK_CNT_STATUS CHECK (CNT_STATUS IN ('A','I','B'))
);

-- TABELA 3: LANCAMENTOS
CREATE TABLE EMUNAH.LANCAMENTOS (
    LCT_LOTE         DECIMAL(6, 0)   NOT NULL,
    LCT_NSEQ         DECIMAL(6, 0)   NOT NULL,
    LCT_AGENCIA      CHAR(4)         NOT NULL,
    LCT_NUM_CONTA    CHAR(8)         NOT NULL,
    LCT_DATA         CHAR(8)         NOT NULL,
    LCT_TIPO         CHAR(1)         NOT NULL,
    LCT_VALOR        DECIMAL(13, 2)  NOT NULL,
    LCT_HISTORICO    VARCHAR(30)     NOT NULL WITH DEFAULT '',
    LCT_CANAL        CHAR(10)        NOT NULL WITH DEFAULT '',
    LCT_STATUS       CHAR(1)         NOT NULL WITH DEFAULT 'P',
    CONSTRAINT PK_LANCAMENTOS PRIMARY KEY (LCT_LOTE, LCT_NSEQ),
    CONSTRAINT FK_LANCTO_CONTAS FOREIGN KEY (LCT_AGENCIA, LCT_NUM_CONTA)
        REFERENCES EMUNAH.CONTAS (CNT_AGENCIA, CNT_NUM_CONTA),
    CONSTRAINT CK_LCT_TIPO   CHECK (LCT_TIPO   IN ('C','D')),
    CONSTRAINT CK_LCT_STATUS CHECK (LCT_STATUS IN ('P','V','R','C')),
    CONSTRAINT CK_LCT_VALOR  CHECK (LCT_VALOR  >= 0)
);

-- TABELA 4: EXTRATO
CREATE TABLE EMUNAH.EXTRATO (
    EXT_AGENCIA      CHAR(4)         NOT NULL,
    EXT_NUM_CONTA    CHAR(8)         NOT NULL,
    EXT_DATA_MOVTO   CHAR(8)         NOT NULL,
    EXT_NSEQ         DECIMAL(6, 0)   NOT NULL,
    EXT_TIPO         CHAR(1)         NOT NULL,
    EXT_DESCRICAO    VARCHAR(30)     NOT NULL WITH DEFAULT '',
    EXT_VALOR        DECIMAL(13, 2)  NOT NULL,
    EXT_SALDO_APOS   DECIMAL(13, 2)  NOT NULL,
    EXT_CANAL        CHAR(10)        NOT NULL WITH DEFAULT '',
    EXT_DT_CARGA     TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_EXTRATO PRIMARY KEY (EXT_AGENCIA, EXT_NUM_CONTA, EXT_DATA_MOVTO, EXT_NSEQ),
    CONSTRAINT FK_EXTRATO_CONTAS FOREIGN KEY (EXT_AGENCIA, EXT_NUM_CONTA)
        REFERENCES EMUNAH.CONTAS (CNT_AGENCIA, CNT_NUM_CONTA),
    CONSTRAINT CK_EXT_TIPO CHECK (EXT_TIPO IN ('C','D'))
);

-- TABELA 5: REJEITOS
CREATE TABLE EMUNAH.REJEITOS (
    REJ_ID           INTEGER         NOT NULL GENERATED ALWAYS AS IDENTITY,
    REJ_AGENCIA      CHAR(4)         NOT NULL,
    REJ_NUM_CONTA    CHAR(8)         NOT NULL,
    REJ_DATA_LANCTO  CHAR(8)         NOT NULL,
    REJ_TIPO_LANCTO  CHAR(1)         NOT NULL,
    REJ_VALOR        DECIMAL(13, 2)  NOT NULL,
    REJ_NSEQ_ORIG    DECIMAL(6, 0)   NOT NULL,
    REJ_COD_MOTIVO   CHAR(4)         NOT NULL,
    REJ_DESC_MOTIVO  VARCHAR(40)     NOT NULL,
    REJ_PROGRAMA     CHAR(8)         NOT NULL,
    REJ_DATA_REJEITO CHAR(8)         NOT NULL,
    REJ_HORA_REJEITO CHAR(8)         NOT NULL,
    CONSTRAINT PK_REJEITOS PRIMARY KEY (REJ_ID),
    CONSTRAINT CK_REJ_TIPO   CHECK (REJ_TIPO_LANCTO IN ('C','D')),
    CONSTRAINT CK_REJ_MOTIVO CHECK (REJ_COD_MOTIVO IN ('R001','R002','R003','R004','R005','R006'))
);

-- TABELA 6: AUDITORIA
CREATE TABLE EMUNAH.AUDITORIA (
    AUD_ID           INTEGER         NOT NULL GENERATED ALWAYS AS IDENTITY,
    AU_TIPO_EVENTO   CHAR(5)         NOT NULL,
    AU_PROGRAMA      CHAR(8)         NOT NULL,
    AU_DATA_EVENTO   CHAR(8)         NOT NULL,
    AU_HORA_EVENTO   CHAR(8)         NOT NULL,
    AU_COD_EVENTO    CHAR(10)        NOT NULL,
    AU_CHAVE_REF     CHAR(20)        NOT NULL WITH DEFAULT '',
    AU_MENSAGEM      VARCHAR(60)     NOT NULL,
    AU_COMPLEMENTO   CHAR(10)        NOT NULL WITH DEFAULT '',
    AUD_TIMESTAMP    TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_AUDITORIA PRIMARY KEY (AUD_ID),
    CONSTRAINT CK_AUD_TIPO CHECK (AU_TIPO_EVENTO IN ('INFO','ERRO','REJT','OK','WARN'))
);

-- INDICES
CREATE INDEX EMUNAH.IX_LANCTO_CONTA_DATA ON EMUNAH.LANCAMENTOS (LCT_AGENCIA, LCT_NUM_CONTA, LCT_DATA);
CREATE INDEX EMUNAH.IX_LANCTO_STATUS     ON EMUNAH.LANCAMENTOS (LCT_STATUS);
CREATE INDEX EMUNAH.IX_REJEITOS_CONTA    ON EMUNAH.REJEITOS (REJ_AGENCIA, REJ_NUM_CONTA);
CREATE INDEX EMUNAH.IX_AUDITORIA_PROG    ON EMUNAH.AUDITORIA (AU_PROGRAMA, AU_DATA_EVENTO);

-- INSERTS (EXEMPLOS)
INSERT INTO EMUNAH.CLIENTES (CLI_ID_CLIENTE, CLI_NOME, CLI_CPF, CLI_DATA_NASC, CLI_STATUS, CLI_DATA_CAD) 
VALUES (1, 'JOAO SILVA', '12345678901', '19900101', 'A', '20260312');