//EBJTEST  JOB ,'TESTE COBOL',CLASS=A,MSGCLASS=X,MSGLEVEL=(1,1),
//             NOTIFY=&SYSUID
//*
//* EXECUCAO SIMPLES DE EXERCICIO COBOL
//* TROQUE EXER001 PELO NOME DO SEU PROGRAMA JA COMPILADO
//*
//STEP1    EXEC PGM=EXER001
//STEPLIB  DD DSN=Z77948.EMUNAH.DEV.LOADLIB,DISP=SHR
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
