//EBTESTE  JOB ,'TESTE',CLASS=A,MSGCLASS=X,MSGLEVEL=(1,1)
//STEP0    EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//SYSIN    DD *
  DELETE Z77948.EMUNAH.ARQ.CLIENTE.KSDS
 -
         CLUSTER PURGE
  SET MAXCC=0
  DEFINE CLUSTER -
         (NAME(Z77948.EMUNAH.ARQ.CLIENTE.KSDS) -
          KEYS(5 0) -
          RECORDSIZE(80 80) -
          TRACKS(5 5) -
          SHAREOPTIONS(2 3) -
          INDEXED) -
         DATA -
         (NAME(Z77948.EMUNAH.ARQ.CLIENTE.KSDS.DATA)) -
         INDEX -
         (NAME(Z77948.EMUNAH.ARQ.CLIENTE.KSDS.INDEX))
/*
//STEP1    EXEC PGM=EBTESTE
//STEPLIB  DD DSN=Z77948.EMUNAH.DEV.LOADLIB,DISP=SHR
//CLIENTIN DD DSN=Z77948.EMUNAH.SEED.CLIENTES.SEQ,DISP=SHR
//CLIENTE  DD DSN=Z77948.EMUNAH.ARQ.CLIENTE.KSDS,DISP=OLD
//SYSOUT   DD SYSOUT=*
