//* ------------------------------------------------------------
//* ARQUIVO      : EBALLOC2.jcl
//* CAMINHO LOCAL: jcl/deploy/EBALLOC2.jcl
//* HOST / PDS   : Z77948.EMUNAH.DEV.JCL(EBALLOC2)
//* FINALIDADE:
//* Alocar os datasets novos do redesenho da cadeia batch que
//* ainda nao foram cobertos por EBALLOC nem por EBDEFGDG.
//* Executar uma unica vez, apos EBALLOC e EBDEFGDG.
//*
//* DATASETS COBERTOS POR EBALLOC (nao sao recriados aqui):
//* - ARQ.CTL.STATUS
//*
//* DATASETS COBERTOS POR EBDEFGDG (nao sao recriados aqui):
//* - ARQ.SALDO.GDG
//* - ARQ.EXTRATO.GDG
//* - BKP.CLIENTE.GDG
//* - BKP.CONTA.GDG
//* - BKP.AUDIT.GDG
//* - BKP.REJEITOS.GDG
//*
//* DATASETS CRIADOS POR ESTE JOB:
//* - ARQ.CTL.PROCDATE         PS FB LRECL=80
//* - ARQ.ACCR.MOV.SEQ         PS FB LRECL=120
//* - ARQ.ENTRADA.TRAILER.SEQ  PS FB LRECL=80
//* - PARM.JUROS.CONFIG        PO FB LRECL=80
//* ------------------------------------------------------------
//EBALLOC2 JOB ,'EMUNAH ALOC2',CLASS=A,MSGCLASS=X,MSGLEVEL=(1,1)
//*
//* === STEP 1: LIMPEZA IDEMPOTENTE (DELETE SE JA EXISTIR) ===
//*
//DELOLD   EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//SYSIN    DD *
  DELETE 'Z77948.EMUNAH.ARQ.CTL.PROCDATE'        NONVSAM
  DELETE 'Z77948.EMUNAH.ARQ.ACCR.MOV.SEQ'        NONVSAM
  DELETE 'Z77948.EMUNAH.ARQ.ENTRADA.TRAILER.SEQ' NONVSAM
  DELETE 'Z77948.EMUNAH.PARM.JUROS.CONFIG'       NONVSAM
  SET MAXCC = 0
/*
//*
//* === STEP 2: SEQUENCIAIS DE CONTROLE E MOVIMENTO ===
//*
//ALOCPS   EXEC PGM=IEFBR14
//CTLPROC  DD DSN=Z77948.EMUNAH.ARQ.CTL.PROCDATE,
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(TRK,(1,1)),
//             DCB=(RECFM=FB,LRECL=80,BLKSIZE=0)
//ACCRMOV  DD DSN=Z77948.EMUNAH.ARQ.ACCR.MOV.SEQ,
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(TRK,(10,5)),
//             DCB=(RECFM=FB,LRECL=120,BLKSIZE=0)
//ENTTRLR  DD DSN=Z77948.EMUNAH.ARQ.ENTRADA.TRAILER.SEQ,
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(TRK,(1,1)),
//             DCB=(RECFM=FB,LRECL=80,BLKSIZE=0)
//*
//* === STEP 3: PDS DE PARAMETROS ===
//*
//ALOCPDS  EXEC PGM=IEFBR14
//PARMJUR  DD DSN=Z77948.EMUNAH.PARM.JUROS.CONFIG,
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(TRK,(5,2,5)),
//             DCB=(RECFM=FB,LRECL=80,BLKSIZE=0,DSORG=PO)
//*
//* === STEP 4: VERIFICA ALOCACAO ===
//*
//VERIFY   EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//SYSIN    DD *
  LISTCAT ENT('Z77948.EMUNAH.ARQ.CTL.PROCDATE')        ALL
  LISTCAT ENT('Z77948.EMUNAH.ARQ.ACCR.MOV.SEQ')        ALL
  LISTCAT ENT('Z77948.EMUNAH.ARQ.ENTRADA.TRAILER.SEQ') ALL
  LISTCAT ENT('Z77948.EMUNAH.PARM.JUROS.CONFIG')       ALL
/*
