//* ------------------------------------------------------------
//* ARQUIVO      : EBDEFGDG.jcl
//* CAMINHO LOCAL: jcl/deploy/EBDEFGDG.jcl
//* HOST / PDS   : Z77948.EMUNAH.DEV.JCL(EBDEFGDG)
//* FINALIDADE:
//* Definir as bases GDG (Generation Data Groups) utilizadas
//* pelos jobs do laboratorio EMUNAH.
//* Executar uma unica vez apos o EBALLOC.
//*
//* GDGs CRIADOS:
//* - ARQ.EXTRATO.GDG      (extrato diario)
//* - ARQ.SALDO.GDG        (snapshot de saldos)
//* - ARQ.BKP.CLIENTE.GDG  (backup diario de clientes)
//* - ARQ.BKP.CONTA.GDG    (backup diario de contas)
//* - ARQ.BKP.AUDIT.GDG    (backup de auditoria)
//* - ARQ.BKP.REJEITOS.GDG (backup de rejeitos)
//* ------------------------------------------------------------
//EBDEFGDG JOB ,'EMUNAH DEFGDG',CLASS=A,MSGCLASS=X,MSGLEVEL=(1,1)
//*
//* === STEP 1: DEFINE GDGs ===
//*
//DEFGDG   EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//SYSIN    DD *
  DELETE 'Z77948.EMUNAH.ARQ.EXTRATO.GDG' GDG FORCE
  SET MAXCC = 0
  DEFINE GENERATIONDATAGROUP -
    (NAME('Z77948.EMUNAH.ARQ.EXTRATO.GDG') -
     LIMIT(30) -
     NOEMPTY -
     SCRATCH)

  DELETE 'Z77948.EMUNAH.ARQ.SALDO.GDG' GDG FORCE
  SET MAXCC = 0
  DEFINE GENERATIONDATAGROUP -
    (NAME('Z77948.EMUNAH.ARQ.SALDO.GDG') -
     LIMIT(30) -
     NOEMPTY -
     SCRATCH)

  DELETE 'Z77948.EMUNAH.ARQ.BKP.CLIENTE.GDG' GDG FORCE
  SET MAXCC = 0
  DEFINE GENERATIONDATAGROUP -
    (NAME('Z77948.EMUNAH.ARQ.BKP.CLIENTE.GDG') -
     LIMIT(7) -
     NOEMPTY -
     SCRATCH)

  DELETE 'Z77948.EMUNAH.ARQ.BKP.CONTA.GDG' GDG FORCE
  SET MAXCC = 0
  DEFINE GENERATIONDATAGROUP -
    (NAME('Z77948.EMUNAH.ARQ.BKP.CONTA.GDG') -
     LIMIT(7) -
     NOEMPTY -
     SCRATCH)

  DELETE 'Z77948.EMUNAH.ARQ.BKP.AUDIT.GDG' GDG FORCE
  SET MAXCC = 0
  DEFINE GENERATIONDATAGROUP -
    (NAME('Z77948.EMUNAH.ARQ.BKP.AUDIT.GDG') -
     LIMIT(14) -
     NOEMPTY -
     SCRATCH)

  DELETE 'Z77948.EMUNAH.ARQ.BKP.REJEITOS.GDG' GDG FORCE
  SET MAXCC = 0
  DEFINE GENERATIONDATAGROUP -
    (NAME('Z77948.EMUNAH.ARQ.BKP.REJEITOS.GDG') -
     LIMIT(14) -
     NOEMPTY -
     SCRATCH)
/*
//*
//* === STEP 2: VERIFICA GDGs CRIADOS ===
//*
//VERIFY   EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//SYSIN    DD *
  LISTCAT ENT('Z77948.EMUNAH.ARQ.EXTRATO.GDG')      ALL
  LISTCAT ENT('Z77948.EMUNAH.ARQ.SALDO.GDG')        ALL
  LISTCAT ENT('Z77948.EMUNAH.ARQ.BKP.CLIENTE.GDG')  ALL
  LISTCAT ENT('Z77948.EMUNAH.ARQ.BKP.CONTA.GDG')    ALL
  LISTCAT ENT('Z77948.EMUNAH.ARQ.BKP.AUDIT.GDG')    ALL
  LISTCAT ENT('Z77948.EMUNAH.ARQ.BKP.REJEITOS.GDG') ALL
/*
