//* ------------------------------------------------------------
//* ARQUIVO      : EBRESET.jcl
//* CAMINHO LOCAL: jcl/util/EBRESET.jcl
//* HOST / PDS   : Z77948.EMUNAH.DEV.JCL(EBRESET)
//* FINALIDADE:
//* Resetar o ambiente deletando datasets de saida e backup.
//* Preserva datasets master, de desenvolvimento e de seed.
//*
//* USAR ANTES DE REEXECUTAR A CADEIA BATCH COMPLETA.
//* ------------------------------------------------------------
//EBRESET  JOB ,'EMUNAH RESET',CLASS=A,MSGCLASS=X,MSGLEVEL=(1,1)
//*
//* === STEP 1: DELETAR DATASETS DE SAIDA ===
//*
//DELSAIDA EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//SYSIN    DD *
  DELETE 'Z77948.EMUNAH.ARQ.LANCTO.ESDS' CLUSTER PURGE
  SET MAXCC = 0
  DELETE 'Z77948.EMUNAH.ARQ.REJEITOS.SEQ' NONVSAM PURGE
  SET MAXCC = 0
  DELETE 'Z77948.EMUNAH.ARQ.AUDIT.SEQ' NONVSAM PURGE
  SET MAXCC = 0
  DELETE 'Z77948.EMUNAH.ARQ.SALDO.OUT.SEQ' NONVSAM PURGE
  SET MAXCC = 0
  DELETE 'Z77948.EMUNAH.ARQ.CONCIL.SEQ' NONVSAM PURGE
  SET MAXCC = 0
  DELETE 'Z77948.EMUNAH.ARQ.EXTRATO.SEQ' NONVSAM PURGE
  SET MAXCC = 0
  DELETE 'Z77948.EMUNAH.ARQ.FECHTO.SEQ' NONVSAM PURGE
  SET MAXCC = 0
/*
//*
//* === STEP 2: DELETAR DATASETS DE REPROCESSAMENTO ===
//*
//DELREPR  EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//SYSIN    DD *
  DELETE 'Z77948.EMUNAH.ARQ.REPR.LANCTO.SEQ' NONVSAM PURGE
  SET MAXCC = 0
  DELETE 'Z77948.EMUNAH.ARQ.REPR.REJPERM.SEQ' NONVSAM PURGE
  SET MAXCC = 0
/*
//*
//* === STEP 3: DELETAR BACKUPS ===
//*
//DELBKP   EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//SYSIN    DD *
  DELETE 'Z77948.EMUNAH.BKP.CLIENTE.SEQ' NONVSAM PURGE
  SET MAXCC = 0
  DELETE 'Z77948.EMUNAH.BKP.CONTA.SEQ' NONVSAM PURGE
  SET MAXCC = 0
  DELETE 'Z77948.EMUNAH.BKP.AUDIT.SEQ' NONVSAM PURGE
  SET MAXCC = 0
/*
//*
//* === STEP 4: RECRIAR LANCTO ESDS ===
//*
//RECRIA   EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//SYSIN    DD *
  DEFINE CLUSTER -
    (NAME('Z77948.EMUNAH.ARQ.LANCTO.ESDS') -
     NONINDEXED -
     RECORDS(5000 1000) -
     RECORDSIZE(120 120) -
     SHAREOPTIONS(2 3)) -
    DATA -
    (NAME('Z77948.EMUNAH.ARQ.LANCTO.ESDS.DATA'))
/*
//*
//* === STEP 5: RECRIAR SEQUENCIAIS NECESSARIOS ===
//*
//RECRIASEQ EXEC PGM=IEFBR14
//REJEITOS DD DSN=Z77948.EMUNAH.ARQ.REJEITOS.SEQ,
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(TRK,(5,5)),
//             DCB=(RECFM=FB,LRECL=120,BLKSIZE=0)
//AUDIT    DD DSN=Z77948.EMUNAH.ARQ.AUDIT.SEQ,
//             DISP=(NEW,CATLG,DELETE),
//             UNIT=SYSDA,SPACE=(TRK,(10,5)),
//             DCB=(RECFM=FB,LRECL=120,BLKSIZE=0)
